# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Act.delete_all
# Act.create(act_name:'Oasis', act_details:"Oasis were an English rock band formed in Manchester in 1991. Developed from an earlier group, the Rain, the band originally consisted of Liam Gallagher (vocals and tambourine), Paul \"Bonehead\" Arthurs (guitar), Paul \"Guigsy\" McGuigan (bass guitar), and Tony McCarroll (drums, percussion). They were later joined by Liam's older brother Noel Gallagher (lead guitar and vocals) as a fifth member, becoming the band's settled line-up until April 1995. \nOasis signed to independent record label Creation Records in 1993 and released their record-setting debut album Definitely Maybe (1994). The following year the band recorded (What's the Story) Morning Glory? (1995) with their new and former Starclub drummer Alan White in the midst of a rivalry with Britpop peers Blur in the charts. The Gallagher brothers were featured regularly in tabloid newspapers for their sibling disputes and wild lifestyles. In 1997 Oasis released their third album, Be Here Now (1997), and although it became the fastest-selling album in UK chart history, the album's popularity tapered off quickly, not before selling 8 million copies. McGuigan and Arthurs left Oasis in 1999 as the band went on to record and release Standing on the Shoulder of Giants (2000). After their departures, they were replaced by former Heavy Stereo guitarist/frontman Gem Archer and former Hurricane No. 1 guitarist/frontman Andy Bell who joined the group for the tour in support of Standing on the Shoulder of Giants, which had moderate success. Their fifth studio album Heathen Chemistry (2002) saw Noel Gallagher's releasing strict creative control in the band's output with all members contributing songs, which led to more relaxed recording sessions. In 2004 the band were joined by The Who's drummer Zak Starkey, replacing Alan White, and found renewed success and popularity with Don't Believe the Truth (2005).")

# Act.create(act_name: 'Runrig', act_details: "Runrig are a Scottish Celtic rock group formed in Skye, in 1973 under the name 'The Run Rig Dance Band'. Since its inception, the band's line-up has included songwriters Rory Macdonald and Calum Macdonald. The current line-up also includes longtime members Malcolm Jones, Iain Bayne, and more recently, Bruce Guthro, and Brian Hurren. To date, the band has released thirteen studio albums, with a number of their songs sung in Scottish Gaelic. \nInitially formed as a three-piece dance band, which played wedding receptions, the trio's first performance took place at Kelvin Hall, in Glasgow. \nRunrig's music is often described as a blend of folk and rock music, with the band's lyrics often focusing upon locations, history, politics and people that are unique to Scotland. Songs also make references to agriculture and land conservation. \nSince 1999, the band has gained attention in Canada, following Nova Scotian singer Bruce Guthro's entry to the band.")

# Act.create(act_name:'Gina G', act_details:"Gina G (born Gina Mary Gardiner, 3 August 1970) is an Australian singer who represented the United Kingdom at the Eurovision Song Contest in Oslo 1996, with the song \"Ooh Aah... Just a Little Bit\", which reached #1 in the UK singles chart. The song remains (as of 2015) the last UK Eurovision entry to top the UK charts. The song also reached the US top 20 and earned G a Grammy Award nomination for Best Dance Recording. Her other UK Top 30 hits are \"I Belong to You\" (1996), \"Fresh\" (1997), \"Ti'Amo\" (1997) and \"Gimme Some Love\"")

# Act.create(act_name:'Jurassic 5', act_details: "Jurassic 5 is an American alternative hip hop group formed in 1993 by members of two previous groups (Rebels of Rhythm and Unity Committee): rappers Charles Stewart (Chali 2na), Dante Givens (Akil), Courtenay Henderson (Zaakir aka Soup), Marc Stuart (Marc 7); and disc jockeys Mark Potsic (DJ Nu-Mark) and Lucas Macfadden (Cut Chemist). The six piece crew that was formed, came out of the Los Angeles venue Good Life. The group broke up in 2007, shortly after releasing their fourth LP Feedback, citing \"musical differences,\" but returned to the stage in 2013 and released a new track in 2014. The members have continued to release music, the most recent of which is Nu-Mark's 2014 EP with Pharcyde member Slimkid3 (released on Delicious Vinyl).")

# Act.create(act_name: 'Cast', act_details:"Cast are an English rock band from Liverpool, formed in 1992 by John Power (vocals, guitar) and Peter Wilkinson (backing vocals, bass) after Power left The La's and Wilkinson's former band Shack had split. Following early line-ups with different guitarists and drummers, Liam \"Skin\" Tyson (guitar) and Keith O'Neill (drums) joined Cast in 1993. \nEmerging from the Britpop movement of the mid-1990s, Cast signed to Polydor Records and their debut album All Change (1995) became the highest selling debut album for the label. Further commercial success continued with the albums Mother Nature Calls (1997) and Magic Hour (1999), however a departure in sound on the band's fourth album Beetroot (2001) was met by a poor critical and commercial reaction and led to the band's split two weeks after its release. \nThe band reformed in November 2010 and released their fourth album Troubled Times in November 2011. Bassist Peter Wilkinson confirmed his departure from the band in March 2015, following his abrupt departure from a previous tour in December 2014. \nNoel Gallagher of Oasis described watching the band live as being like a \"religious experience\" and they were labelled \"The Who of the 90's\". It has been suggested that the name \"Cast\" was taken from the final word on The La's eponymous album (the song \"Looking Glass\" ends with the repeated line \"The change is cast\"); John Power has since confirmed this to be true, stating that he avoided answering this question for some time.")

# Act.create(act_name:'Quannum Projects', act_details: "Quannum Projects (aka Quannum MCs) is a hip hop collective based in the San Francisco Bay Area. It has been active since 1992, when it was formed at UC Davis under the moniker Solesides Records. It is also the name of the independent record label that releases their records, as well as those of a number of other artists. The label continues to be 100% independently owned and operated.")

# Act.create(act_name: 'Justin Buttface', act_details: "Justin Drew Bieber (/ˈbiːbər/; born March 1, 1994) is a Canadian singer, songwriter, and record producer. Bieber released his debut EP, My World, in late 2009. It was certified platinum in the U.S. He became the first artist to have seven songs from a debut record chart on the Billboard Hot 100. Bieber released his first full-length studio album, My World 2.0, in 2010. It debuted at or near number one in several countries and was certified triple platinum in the U.S. It was preceded by his most successful single to date, the certified 12 times platinum \"Baby\". \nFollowing his debut album he had his first headlining tour, the My World Tour, released the remix albums My Worlds Acoustic and Never Say Never – The Remixes -- and the 3D biopic-concert film Justin Bieber: Never Say Never. He released his second studio album, Under the Mistletoe, in November 2011, when it debuted at number one on the Billboard 200. Bieber released his third studio album, Believe, in 2012. His fourth studio album Purpose was released in November 2015. His U.S. album and singles sales total 44.7 million. \nHe has won numerous fan-voted awards, including American Music Award for Artist of the Year in 2010 and 2012. His fan base, dubbed \"beliebers\", largely consists of early to mid-adolescent girls. He was listed three times by Forbes magazine among the top ten most powerful celebrities in the world in 2011, 2012, and 2013.")

# Act.create(act_name: 'British INdoor Gymnastics Championships', act_details: "It was founded in 1888 as the Amateur Gymnastics and Fencing Association. Gymnastics had been adopted in this country, having been invented in Germany by Friedrich Ludwig Jahn, to improve the health and fitness of its soldiers. The rings, pommel horse, parallel bars, and horizontal bar were developed by Jahn. In the late 1800s gymnastics became popular for men thanks to the Army Physical Training Corps which was formed in 1860. Walter Tysall won the men's silver medal in the 1908 Olympics. After this time the Swedish form of gymnastics became more popular, a more artistic version developed by Pehr Henrik Ling which was for men and women, and needed little apparatus. \nWomen first competed at the Olympics in gymnastics at the 1928 Olympics in Amsterdam, where the British women's team took the bronze – its best performance. \nAfter the Second World War, the German and Swedish forms of gymnastics were combined. The 1960 Rome Olympics were the first to be televised, and this led to a greater interest in Britain of gymnastics. This Olympics had been dominated by Russian female gymnasts. In 1963 the Amateur Gymnastics Association became the British Amateur Gymnastics Association, and the BAGA first received a government grant, allowing it to pay coaches, and appoint a full-time national coach, Wray Stuart. He developed the BAGA Awards, a proficiency scheme for young gymnasts, which was adopted by seventy other countries. \nThe BAGA Awards started to produce results for Britain. Gymnastics was given superstar status by the 1972 Olympics at Munich. \nAt the 2012 London Olympics, the Men's Artistic Gymnastics team won Bronze with individual Silver for Louis Smith and Bronze for Max Whitlock on Pommel and individual Bronze for Beth Tweddle on Uneven bars.")

# Act.create(act_name: 'Britain\'s Strongest Man', act_details: "In a history that has close parallels with that of the World's Strongest Man competition, the BSM competition has had a number of sponsors and, at different times, has had to vie with rival competitions that also claim to produce the strongest man in Britain as their champion. The inaugural competition was in 1979 and was organised by TWI. It was covered by the BBC. The final contest involved the field athletes Geoff Capes and Jim Whitehead, weightlifter Andy Drzewiecki, powerlifter Ray Nobile, Highland Games specialists Bill Anderson and Grant Anderson, wrestler Big Pat Roach, and Tosher Killingback; it was won by Geoff Capes. The contestants were there by invitation. The format continued until 1984. There was then a break of three years, from 1985 through 1988, before the competition returned in 1989. In 1986, there was a \"Britain's Most Powerful Man\" and, in 1988, a competition was organised by Geoff Capes and David Webster to find a successor to Geoff Capes, called the John Smith's Trial of Strength. The results of these competitions are often deemed to be equivalent to Britain's Strongest Man given the lack of a competition in those years. The IFSA, after its creation in the mid-nineties, managed the event but parted company with TW1 after the completion of the 2004 event. TW1 have managed to have the event televised since the BBC opted out in 2004, with Sky One covering it in 2005, and Five in 2007 and 2008. The competition is currently sponsored by Met-Rx.")

# Act.create(act_name: 'The Libertimes', act_details: "The Libertines are an English rock band, formed in London in 1997 by frontmen Carl Barât (vocals/guitar) and Pete Doherty (vocals/guitar). The band, centred on the songwriting partnership of Barât and Doherty, has also included John Hassall (bass) and Gary Powell (drums) for most of its recording career. The band was part of the garage rock revival and spearheaded the movement in the UK. \nThe band gained some notoriety in the early 2000s. Although their mainstream success was initially limited, their profile soon grew, culminating in a No. 2 single and No. 1 album on the UK Charts. In December 2004, their self-titled second album was voted the second best album of the year by NME magazine. The first two of their full-length LPs were produced by Mick Jones, of the British punk band The Clash. \nIn spite of their critical and controversial success as well as decent commercial success, the band's music was often eclipsed by its internal conflicts, stemming from Doherty's addictions to crack cocaine and heroin, which eventually led to the breakup of the band. Doherty has since stated that the breakup of the band was due to relationship difficulties between Barât and himself that were not related to his drug addictions. The members of The Libertines went on to form new bands with varying degrees of commercial and critical success. \nIn August 2010, the four members of The Libertines reunited to play a series of shows, including slots at the 2010 Reading and Leeds Festivals. The reunion shows received a highly positive response from the press and fans. \nIn April 2014, The Libertines announced they would again reform for a show at London's Hyde Park. In November 2014 the band signed a record deal with Virgin EMI Records, and released their third album, Anthems for Doomed Youth on September 11, 2015")

# Act.create(act_name: 'Elton John', act_details: "Sir Elton Hercules John, CBE (born Reginald Kenneth Dwight, 25 March 1947) is an English singer-songwriter, composer and pianist. He has worked with lyricist Bernie Taupin as his songwriting partner since 1967; they have collaborated on more than 30 albums to date. In his five-decade career Elton John has sold more than 300 million records, making him one of the best-selling music artists in the world. He has more than fifty Top 40 hits, including seven consecutive No. 1 US albums, 58 Billboard Top 40 singles, 27 Top 10, four No. 2 and nine No. 1. For 31 consecutive years (1970–2000) he had at least one song in the Billboard Hot 100. His single \"Candle in the Wind 1997\" sold over 33 million copies worldwide and is the best-selling single in the history of the UK and US singles charts. He has also composed music, produced records, and has occasionally acted in films. John owned Watford Football Club from 1976 to 1987, and 1997 to 2002. He is an honorary Life President of the club, and in 2014 had a stand named after him at the club's home stadium. \nElton John was born Reginald Dwight in 1947, and raised in the Pinner area of London. He learned to play piano at an early age, and by 1962 had formed Bluesology. John met his songwriting partner, Bernie Taupin, in 1967, after they had both answered an advert for songwriters. For two years they wrote songs for other artists, including Roger Cook and Lulu, and John also worked as a session musician for artists such as the Hollies and the Scaffold. In 1968 his debut album, Empty Sky, was released. In 1970 a single, \"Your Song\", from his second album, Elton John, reached the top ten in the UK and the US, his first hit single. He has received six Grammy Awards, five Brit Awards – winning two awards for Outstanding Contribution to Music and the first Brits Icon in 2013 for his \"lasting impact on British culture\", an Academy Award, a Golden Globe Award, a Tony Award, a Disney Legend award, and the Kennedy Center Honors in 2004. In 2004, Rolling Stone ranked him Number 49 on its list of 100 influential musicians of the rock and roll era. In 2013, Billboard ranked him the most successful male solo artist on \"The Billboard Hot 100 Top All-Time Artists\" (third overall behind the Beatles and Madonna). He was inducted into the Rock and Roll Hall of Fame in 1994, is an inductee into the Songwriter's Hall of Fame, and is a fellow of the British Academy of Songwriters, Composers and Authors. Having been named a Commander of the Order of the British Empire in 1996, John was made a Knight Bachelor by Elizabeth II for \"services to music and charitable services\" in 1998. John has performed at a number of royal events, such as the funeral of Princess Diana at Westminster Abbey in 1997, the Party at the Palace in 2002 and the Queen's Diamond Jubilee Concert outside Buckingham Palace in 2012.")

# Act.create(act_name:'Premier League Darts', act_details: "The Premier League Darts is a darts tournament which launched on 20 January 2005 on Sky Sports. The league is now played weekly from February to May, having originally started as a fortnightly fixture. The tournament originally featured seven players and now sees ten of the biggest names from the PDC circuit competing in a double round-robin format, with matches held across the United Kingdom and Ireland at different venues. The top four players in the PDC Order of Merit are joined by six wildcard selections to make up the ten-man field. The current sponsor is Betway. \nThe previous sponsors were McCoy's, Whyte and Mackay, who succeeded Holsten, having signed a three-year contract to support the event in October 2007, and 888.com. The prize fund rose from £265,000 to £340,000 in 2008, steadily increasing each year for a prize fund of £550,000 in 2014. The winner currently receives £150,000. \nPhil Taylor has dominated this event, winning six of the eleven competitions to date. He went unbeaten throughout the first three seasons before James Wade ended his 44 match run in the first match of the 2008 season. A new champion was to be crowned after Mervyn King defeated him in the 2009 semi-finals. Wade defeated King 13–8 in the final, to pick up the £125,000 first prize. Phil Taylor defeated James Wade the following season to claim his fifth title in the competition in 2010, however he was defeated in the semi-final of the 2011 tournament. Gary Anderson became champion in his debut season. by defeating Adrian Lewis in a repeat of the world championship final earlier that year. Phil Taylor reclaimed the title the following year, after defeating Simon Whitlock in the 2012 final, but lost the 2013 final to Michael van Gerwen. A year later, Taylor - who lost four of his first five games of the season and only secured qualification to the playoffs on the final league night - lost to eventual champion Raymond van Barneveld in the semi-finals.
# ")

# Act.create(act_name: 'Boxing', act_details: "Boxing is a martial art and combat sport in which two people throw punches at each other, usually with gloved hands. Historically, the goals have been to weaken and knock down the opponent. \nAmateur boxing is both an Olympic and Commonwealth sport and is a common fixture in most international games—it also has its own World Championships. Boxing is supervised by a referee over a series of one- to three-minute intervals called rounds. The result is decided when an opponent is deemed incapable to continue by a referee, is disqualified for breaking a rule, resigns by throwing in a towel, or is pronounced the winner or loser based on the judges' scorecards at the end of the contest. In the event that both fighters gain equal scores from the judges, the fight is considered a draw. \nWhile people have fought in hand-to-hand combat since before the dawn of history, the origin of boxing as an organized sport may be its acceptance by the ancient Greeks as an Olympic game in BC 688. Boxing evolved from 16th- and 18th-century prizefights, largely in Great Britain, to the forerunner of modern boxing in the mid-19th century, again initially in Great Britain and later in the United States.")

# Act.create(act_name: 'Russel Howard', act_details: "Russell Joseph Howard (born 23 March 1980) is an English comedian, television and radio presenter and actor, best known for his TV show Russell Howard's Good News and his appearances on the topical panel TV show Mock the Week. He won \"Best Compère\" at the 2006 Chortle Awards and was nominated for an if.comedy award for his 2006 Edinburgh Festival Fringe show.")

# Act.create(act_name: 'kevin bridges', act_details: "Kevin Andrew Bridges (born 13 November 1986) is a Scottish stand-up comedian. He has appeared on many comedy television shows including Would I Lie to You?, Have I Got News for You and has performed at Live at the Apollo. Kevin Bridges: What's the Story? was based on his stand-up routines \nBridges began performing on the small stage when he left school shortly after turning 17, doing stand-up comedy gigs at The Stand Comedy Club in Glasgow and then throughout the UK. Bridges said he was inspired to try stand up after reading Frank Skinner's autobiography. At 18, he reached the final of Channel 5's So You Think You're Funny competition at the Edinburgh Fringe. He performed at the 2008 Edinburgh Festival Fringe. Bridges appeared on Michael McIntyre's Comedy Roadshow on the BBC, where he performed at the Edinburgh Playhouse. \nIn 2010, Bridges took part in Channel 4's Comedy Gala, a benefit show held in aid of Great Ormond Street Children's Hospital, filmed live at the O2 Arena in London. \nHis debut DVD, titled Kevin Bridges: The Story So Far... Live in Glasgow, was released on 22 November 2010.")

# Act.create(act_name: 'The Royal BAllet', act_details: "The Royal Ballet is an internationally renowned classical ballet company, based at the Royal Opera House in Covent Garden, London, UK. The largest of the four major ballet companies in Great Britain, the Royal Ballet was founded in 1931 by Dame Ninette de Valois, it became the resident ballet company of the Royal Opera House in 1946 and was granted a royal charter in 1956, becoming recognised as Britain's flagship national ballet company. \nThe Royal Ballet was one of the foremost ballet companies of the 20th century, and continues to be one of the world's most famous ballet companies to this day, generally noted for its artistic and creative values. The company employs approximately 100 dancers and has purpose built facilities within the Royal Opera House. The official associate school of the company is the Royal Ballet School, and it also has a sister company, the Birmingham Royal Ballet, which operates independently. The Prima ballerina assoluta of the Royal Ballet is the late Dame Margot Fonteyn.")

# Act.create(act_name:'Europes\'s Strongets Man', act_details: "Europe's Strongest Man is an annual strength athletics competition which began in 1980. The event is held in various locations throughout Europe, and features exclusively European strongman competitors. Mariusz Pudzianowski currently holds the record for most wins with 6 titles. Zydrunas Savickas, Geoff Capes and Riku Kiri each hold 3 titles. As of 2010, the Europe's Strongest Man contest has become a part of the Giants Live season of annual grand prix events. The contest serves as a qualifying event for the World's Strongest Man contest, with the top 3 placings qualifying for that year's WSM contest.")

Booking.delete_all

# Event.delete_all
# #Oasis MEN Arena
# Event.create(act_id: 50,venue_id: 16,event_start_time: '2016-02-10 19:00',event_end_time: "2016-02-10 23:00", event_price: 50.00, event_details: 'What\'s the Story Morning Glory Tour')

# #Runrig SSE
# Event.create(act_id: 51,venue_id: 19,event_start_time: "2016-02-11 19:00",event_end_time: "2016-02-11 23:00", event_price: 55.00, event_details: 'The Big Wheel Tour')

# #Gina G
# Event.create(act_id: 52,venue_id: 18,event_start_time: "2016-02-12 19:00",event_end_time: "2016-02-12 23:00", event_price: 10.00, event_details: 'Just A Little Bit Tour')

# #Jurassic 5
# Event.create(act_id: 53,venue_id: 18,event_start_time: "2016-02-12 19:00",event_end_time: "2016-02-13 01:00", event_price: 40.00, event_details: 'J5 Smash It Tour')

# #Cast
# Event.create(act_id: 54,venue_id: 22,event_start_time: "2016-02-13 19:00",event_end_time: "2016-02-13 22:00", event_price: 35, event_details: 'Wondering Tour')

# #Quannum Projects
# Event.create(act_id: 55,venue_id: 21,event_start_time: "2016-02-15 21:00",event_end_time: "2016-02-16 04:00", event_price: 35, event_details: 'Spectrum Tour')

# #Justin Buttface
# Event.create(act_id: 56,venue_id: 24,event_start_time: "2016-02-16 14:00",event_end_time: "2016-02-16 15:00", event_price: 0,event_details: "Stupid Little Boy Crashes A Ferrari Tour")

# #Gymnastics
# Event.create(act_id: 57,venue_id: 23,event_start_time: "2016-02-17 11:00",event_end_time: "2016-02-17 17:00", event_price: 60,event_details: "Rythemic Gymnastics Final")

# #BSM Dome
# Event.create(act_id: 58,venue_id: 15,event_start_time: "2016-01-29 11:00",event_end_time: "2016-01-29 16:00", event_price: 29,event_details: "Britain\'s Strongest Man Final")

# #libertines
# Event.create(act_id: 59,venue_id: 23,event_start_time: "2016-02-18 19:00" ,event_end_time: "2016-02-18 22:00",event_price: 45.00, event_details: 'Music When The Lights Go Out Tour')

# #elton john o2
# Event.create(act_id: 60,venue_id: 17,event_start_time: "2016-02-18 19:00",event_end_time: "2016-02-18 23:00", event_price: 85,event_details: 'Your Song Tour')

# #darts
# Event.create(act_id: 61,venue_id: 15,event_start_time: "2016-02-19 20:00",event_end_time: "2016-02-19 22:00", event_price: 15, event_details:'British Darts Championships Final')

# #boxing
# Event.create(act_id: 62,venue_id: 18,event_start_time: "2016-02-19 23:00",event_end_time: "2016-02-20 03:00", event_price: 150, event_details: 'Hay Day')

# #r howard MEN
# Event.create(act_id: 63,venue_id: 16,event_start_time: "2016-02-22 20:00",event_end_time: "2016-02-22 23:00", event_price: 75, event_details: 'Wonderbox Tour')

# #kevin bridges
# Event.create(act_id: 64,venue_id: 19,event_start_time: "2016-02-22 20:00",event_end_time: "2016-02-22 23:00", event_price: 49, event_details: 'Build A Bridge Tour')

# #ballet
# Event.create(act_id: 65,venue_id: 20,event_start_time: "2016-02-23 19:00",event_end_time: "2016-02-23 22:00", event_price: 65, event_details: 'Swan Lake')

# #ESM headdingley
# Event.create(act_id: 66,venue_id: 14,event_start_time: "2016-06-20 11:00",event_end_time: "2016-06-20 16:00", event_price: 45, event_details: 'Europe\'s Strongest Man')

# Genre.delete_all
#   Genre.create(title:'Sport') 1
#   Genre.create(title:'Music') 2
#   Genre.create(title: 'Comedy') 3
#   Genre.create(title: 'Theatre & The Arts') 4

# EventGenre.delete_all
#   EventGenre.create(event_id:4, genre_id:2)
#   EventGenre.create(event_id:5,genre_id:2)
#   EventGenre.create(event_id:6,genre_id:2)
#   EventGenre.create(event_id:7,genre_id:2)
#   EventGenre.create(event_id:8,genre_id:2)
#   EventGenre.create(event_id:9,genre_id:2)
#   EventGenre.create(event_id:10,genre_id:2)
#   EventGenre.create(event_id:11,genre_id:1)
#   EventGenre.create(event_id:12,genre_id:1)
#   EventGenre.create(event_id:13,genre_id:2)
#   EventGenre.create(event_id:14,genre_id:2)
#   EventGenre.create(event_id:15,genre_id:1)
#   EventGenre.create(event_id:16,genre_id:1)
#   EventGenre.create(event_id:17,genre_id:3)
#   EventGenre.create(event_id:18,genre_id:3)
#   EventGenre.create(event_id:19,genre_id:4)
#   EventGenre.create(event_id:20,genre_id:1)

User.delete_all
  User.create(email: 'user1@email.com', password:'Password1')
  User.create(email: 'user2@email.com', password:'Password1')
  User.create(email: 'user3@email.com', password:'Password1')
  User.create(email: 'admin@email.com', password:'Password1', role: 'admin')

# Venue.delete_all
# Venue.create(venue_name: 'Carnegie Stadium', venue_details: "Leeds Rhinos have only ever played at Headingley since their formation in 1865. They ground share with rugby union side Yorkshire Carnegie who were formed in 1991. Both clubs and the ground itself are owned by Leeds Rugby. The rugby ground is also on the same site as the cricket ground operated by Yorkshire CCC. The North Stand of the rugby ground back onto the cricket ground. The Carnegie Stand was built in 2006 to incorporate executive boxes into Headingley and also expanded the capacity to 21,000 adding extra seating on the top tier and terrecing on the bottom. \nBoth Yorkshire CCC and Leeds Rugby are looking at redeveloping the North Stand as part of the redevelopment of the cricket ground to rebuild it and to add the seating on both sides to expand the capacity of both grounds and possibly add more executive boxes to the stadium. The club has also looked into the possibility of redeveloping the South Stand and the Western Terrece, however any redevelopment or expansion of the Western Terrece would require the demolition of housing and rerouting of a public right of way.", venue_location: 'Leeds', venue_capacity: 100)

# Venue.create(venue_name: 'The Doncaster Dome', venue_details: "The Dome Leisure Centre is an arena and leisure centre in Doncaster, England, informally known as The Dome or Doncaster Dome. It has a swimming complex, bars, a sports arena that is also used as an event venue and the United Kingdom's first ever split level ice skating rink. \nThe Dome as a concept was first conceived in 1985, by Doncaster Metropolitan Borough Council. The aim of the project was to inject capital and confidence into the community of Doncaster. The Dome was to act as a catalyst for the economic and qualitative regeneration of Doncaster – at a time when the economic climate of Doncaster was depressed, the Dome was to herald a new age. \nThe building was designed by architect Faulkner Brown, and work was underway by November 1986, taking a little under three years for completion with the building officially being declared 'finished' in August 1989. The building was officially opened by HRH Diana, Princess of Wales on 26 November 1989. In total, the project cost £26 million. \nIn 2005 and 2006, it played host to the Premier League Darts.", venue_location: 'Doncaster', venue_capacity: 100)

# Venue.create(venue_name: 'Manchester Evening News Arena', venue_details: "The Manchester Arena is an indoor arena in Hunts Bank, Manchester, England. Situated immediately north of the city centre, most of the arena is situated above Manchester Victoria station in air rights space. \nThe arena has the highest seating capacity of any indoor venue in the United Kingdom, and fourth largest in the European Union with a capacity of 21,000 and is one of the world's busiest indoor arenas, hosting music and sporting events such as boxing and swimming. The arena was a key part of Manchester's bids to host the Olympic Games in 1996 and 2000 and was eventually used for the 2002 Commonwealth Games.", venue_location: 'Manchester', venue_capacity: 100)

# Venue.create(venue_name: 'The O2 Arena', venue_details: "The O2 Arena, referred to as North Greenwich Arena in the context of the 2012 Summer Olympics and 2012 Summer Paralympics, is a multi-purpose indoor arena located in the centre of The O2, a large entertainment complex on the Greenwich Peninsula in London. It is named after its main sponsor, the telecommunications company O2. \nThe O2 Arena has the second-highest seating capacity of any indoor venue in the UK, behind the Manchester Arena, but took the crown of the world's busiest music arena from New York's Madison Square Garden in 2008. The closest underground station to the venue is the North Greenwich station on the Jubilee line.", venue_location: 'London', venue_capacity: 100)

# Venue.create(venue_name: 'ExCeL London', venue_details: "ExCeL London (Exhibition Centre London) (often referred to as the ExCeL Exhibition Centre) is an exhibitions and international convention centre in the London Borough of Newham. It is located on a 100-acre (0.40 km2) site on the northern quay of the Royal Victoria Dock in London Docklands, between Canary Wharf and London City Airport. The ICC Auditorium also hosted Miss World 2014 on December 14, 2014.", venue_location: 'London', venue_capacity: 100)

# Venue.create(venue_name: 'SSE Glasgow', venue_details: "The SSE Hydro is an arena located in Glasgow, Scotland, on the site of the Scottish Exhibition and Conference Centre (SECC). The arena has a capacity of 13,000. The arena officially opened on 30 September 2013, with a concert by Rod Stewart. It was designed by the London-based architects Foster + Partners and named after SSE plc. \nThe SSE Hydro handled 1,045,344 ticket sales in 2014, making it the second-busiest music arena in the world in terms of ticket sales, behind only London's The O2 Arena. This makes the arena busier than Manchester's Manchester Arena and the famous Madison Square Garden in New York.", venue_location: 'Glasgow', venue_capacity: 100)

# Venue.create(venue_name: 'Birmingham Hippodrome Theatre', venue_details: "The Birmingham Hippodrome is a theatre situated on Hurst Street in the Chinese Quarter of Birmingham, England. \nAlthough best known as the home stage of the Birmingham Royal Ballet, it also hosts a wide variety of other performances including visiting opera and ballet companies, touring West End shows, pantomime and drama. \nThe Hippodrome is the venue for West End touring theatrical shows, such as Wicked, Chitty Chitty Bang Bang, The Lion King, Mary Poppins and We Will Rock You. The pantomime from the company QDOS is held there annually. Celebrity fashion guru Gok Wan, John Partridge, Stephanie Beacham, Paul Zerdin, Matt Slack and Danielle Hope starred in the 2013/14 production of Snow White and the Seven Dwarfs, the theatre's most successful pantomime in ten year. The theatre's Chief Executive is Fiona Allen. \nWith a regular annual attendance of over 600,000, the Hippodrome is the busiest single theatre in the United Kingdom, and the busiest venue for dance outside London.",venue_location: 'Birmingham', venue_capacity: 100)

# Venue.create(venue_name: 'The Grand Theartre', venue_details: "The Grand was designed by Victorian theatre architect Frank Matcham and was opened in 1894 after a construction period of seven months, at a cost of £20,000 between December 1893 and July 1894. The project was conceived and financed by local theatre manager Thomas Sergenson who had been using the site of the Grand for several years to stage a circus. He had also transformed the fortunes of other local theatres. \nMatcham's brief was to build Sergenson the \"prettiest theatre in the land\". The Grand was Matcham's first theatre to use an innovative 'cantilever' design to support the tiers, thereby reducing the need for the usual pillars and so allowing clear views of the stage from all parts of the auditorium. \nSergenson's successful directorship of the theatre ended in 1909 when he sold the operation to the Blackpool Tower Company for a considerable profit. \nThe success of the Grand continued through World War I and on until the 1930s. The theatre now faced stiff competition from the newly introduced talking movies and the building was operated as a cinema outside the summer tourist season. This practice continued until 1938 when the nearby Opera House was constructed. \nThe Grand was able to stay open during World War II but the post-war rise in the popularity of television was probably the cause of the theatre's dwindling popularity toward the 1960s.[citation needed] Plans were filed for the demolition of the historic site in 1972 but the Grand's status as a Grade II listed building was sought and obtained by a group of friends, thereby preventing this from taking place. An agreement was reached with the Grand's owners, EMI, that a refurbishment of the then unused building would take place if it could be used as a bingo hall. After three years of bingo use, the group of friends, now called the Friends of the Grand, with the support of Blackpool Borough Council negotiated to lease and eventually buy the theatre back from EMI over a period of a few years. The purchase was complete by 1 October 1980 and a refurbishment, achieved partly through voluntary effort, was begun. Finally, on 23 March 1981 the Grand re-opened as a theatre once again to stage an Old Vic performance of William Shakespeare's The Merchant of Venice featuring Timothy West and Prunella Scales. The theatre's return was further confirmed in May of the same year when a Royal Variety Performance was staged in the presence of Charles, Prince of Wales.", venue_location: 'Blackpool', venue_capacity: 100)

# Venue.create(venue_name: 'Wemberley Stadium', venue_details: "Wembley Stadium is a football stadium in Wembley, London, England, which opened in 2007, on the site of the original Wembley Stadium, which was demolished from 2002–2003. The stadium hosts major football matches including the FA Cup Final and home matches of the England national football team. The stadium is also the secondary home stadium facility for the American football franchise Jacksonville Jaguars of the National Football League (NFL). \nWembley Stadium is a UEFA category four stadium. With 90,000 seats, it is the second-largest stadium in Europe and the largest stadium in the United Kingdom. It is owned by The Football Association through its subsidiary Wembley National Stadium Ltd (WNSL). \nDesigned by HOK Sport and Foster and Partners, it includes a partially retractable roof and the 134-metre-high (440 ft) Wembley Arch. The stadium was built by Australian firm Multiplex at a cost of £798 million. \nIn addition to the FA Cup Final, the stadium hosts the season-opening FA Community Shield, the League Cup Final, the Football League Trophy and the Football League play-offs. It hosted the 2011 and 2013 UEFA Champions League Final, the Gold medal matches at the 2012 Olympic Games football tournament, and will host both the semi-finals and final of UEFA Euro 2020. The stadium also hosts the rugby league Challenge Cup Final, the NFL International Series and music concerts.", venue_location: 'London', venue_capacity: 100)

# Venue.create(venue_name: 'Sheffield Arena', venue_details: "Sheffield Arena (originally Sheffield Arena and formerly Hallam FM Arena and Motorpoint Arena Sheffield) is an arena located in Sheffield, England. It is situated near Rotherham, Sheffield City Centre, Attercliffe, Meadowhall and the Centertainment. \nThe arena opened as Sheffield Arena and was renamed Hallam FM Arena, but returned to its original name as of 1 November 2007. On 9 August 2010, Sheffield Arena was officially renamed Motorpoint Arena Sheffield, after the Derby based car sales company invested £1 million to rename the venue. It is used for big name concerts and sporting events. It is home to the Sheffield Steelers Ice Hockey Club. In August 2015 the arena was once again rebranded as Sheffield Arena.")
